-- 1. Total number of products sold by a seller
SELECT 
    SUM(OrderItem.Quantity) AS TotalProductsSold
FROM 
    OrderItem
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND OrderItem.OrderID IN (
        SELECT OrderID FROM `Order` WHERE OrderDate BETWEEN %s AND %s
    );

-- 2. Total revenue generated by a seller
SELECT 
    SUM(OrderItem.Quantity * OrderItem.PriceAtPurchase) AS TotalRevenue
FROM 
    OrderItem
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND OrderItem.OrderID IN (
        SELECT OrderID FROM `Order` WHERE OrderDate BETWEEN %s AND %s
    );

-- 3. Total number of orders received by a seller
SELECT 
    COUNT(DISTINCT `Order`.OrderID) AS TotalOrders
FROM 
    `Order`
JOIN 
    OrderItem ON `Order`.OrderID = OrderItem.OrderID
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND `Order`.OrderDate BETWEEN %s AND %s;

-- 4. Total quantity of each product sold by a seller
SELECT 
    Product.ProductName,
    SUM(OrderItem.Quantity) AS TotalQuantitySold
FROM 
    OrderItem
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND OrderItem.OrderID IN (
        SELECT OrderID FROM `Order` WHERE OrderDate BETWEEN %s AND %s
    )
GROUP BY 
    Product.ProductName;

-- 5. Average price per order for a seller
SELECT 
    AVG(`Order`.TotalAmount) AS AverageOrderPrice
FROM 
    `Order`
WHERE 
    `Order`.OrderID IN (
        SELECT OrderItem.OrderID 
        FROM OrderItem 
        JOIN Product ON OrderItem.ProductID = Product.ProductID
        WHERE Product.SellerID = %s
    )
    AND `Order`.OrderDate BETWEEN %s AND %s;

-- 6. Total number of distinct products sold by a seller
SELECT 
    COUNT(DISTINCT OrderItem.ProductID) AS TotalDistinctProductsSold
FROM 
    OrderItem
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND OrderItem.OrderID IN (
        SELECT OrderID FROM `Order` WHERE OrderDate BETWEEN %s AND %s
    );

-- 7. The most sold product by a seller
SELECT 
    Product.ProductName,
    SUM(OrderItem.Quantity) AS TotalQuantitySold
FROM 
    OrderItem
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND OrderItem.OrderID IN (
        SELECT OrderID FROM `Order` WHERE OrderDate BETWEEN %s AND %s
    )
GROUP BY 
    Product.ProductName
ORDER BY 
    TotalQuantitySold DESC
LIMIT 1;

-- 8. The highest revenue generating product by a seller
SELECT 
    Product.ProductName,
    SUM(OrderItem.Quantity * OrderItem.PriceAtPurchase) AS TotalRevenueGenerated
FROM 
    OrderItem
JOIN 
    Product ON OrderItem.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s 
    AND OrderItem.OrderID IN (
        SELECT OrderID FROM `Order` WHERE OrderDate BETWEEN %s AND %s
    )
GROUP BY 
    Product.ProductName
ORDER BY 
    TotalRevenueGenerated DESC
LIMIT 1;

-- 9. Average product rating received by a seller
SELECT 
    AVG(Review.Rating) AS AverageProductRating
FROM 
    Review
JOIN 
    Product ON Review.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s;

-- 10. Total number of reviews received by a seller
SELECT 
    COUNT(Review.ReviewID) AS TotalReviewsReceived
FROM 
    Review
JOIN 
    Product ON Review.ProductID = Product.ProductID
WHERE 
    Product.SellerID = %s;
